### ISSUE TITLE
fix autolabeler by adding permissions and pull requests events

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/.github#21]
Right now we have supported autolabeler https://github.com/cpp-linter/.github/blob/b7268d7afd1af602b91a4d494478bcd56f4f8e72/.github/release-drafter.yml#L75-L88

but it doesn't work actually. from the docs https://github.com/toolmantim/release-drafter we need to 

- [x] add permission to https://github.com/cpp-linter/.github/commit/b7268d7afd1af602b91a4d494478bcd56f4f8e72
- [x] add pull request events to workflow. e.g.: https://github.com/cpp-linter/cpp-linter-hooks/pull/41

**Comment by 2bndy5** [comment]
Also add rst files for Sphinx docs
```yml
     files: 
       - '*.md' 
       - '*.rst'
```
