### ISSUE TITLE
Generate build provenance attestations

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/.github#28]
It looks like GitHub rolled out their own attestations in beta. I wonder if we could integrate with that. for more details below:

- https://github.com/actions/attest-build-provenance
- https://github.com/cpp-linter/cpp-linter-action/attestations
- https://github.com/orgs/community/discussions/122028
- https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
- https://github.blog/2024-04-30-where-does-your-software-really-come-from/

**Comment by 2bndy5** [comment]
That last link was most helpful to me. I've never been too concerned about verifying "artifacts" that I download over the Internet.

Now that I have a better understanding of provenance attestation, my first thought was the static binaries we are distributing via clang-tools-pip use. This is where I'd start integrating proper attestation. Then we can use such attestation downstream in cpp-linter-action...

Pypi does not support any form of digital signing (that in aware of). Just last year, they dropped their support for PGP signatures.

**Comment by 2bndy5** [comment]
This is complete anyway, right?
